# Uncomment the next line to define a global platform for your project
platform :ios, '14.3'

target 'MeLiCodeChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MeLiCodeChallenge
  pod 'Kingfisher', '~> 6.0'

  target 'MeLiCodeChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MeLiCodeChallengeUITests' do
    # Pods for testing
  end

end
